name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Custom Config
        run: |
          sed -i 's/gitRepo = ""/gitRepo = "https:\/\/github.com\/zhouxhere\/zhouxhere.git"/g' config.toml
          sed -i 's/icp = /# icp = /g' config.toml

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          personal_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          external_repository: zhouxhere/zhouxhere.github.io
          publish_dir: ./public
          publish_branch: master  # default: gh-pages